### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by grammoboy2** [zrythm/ZLFO#1]
ZLFO$ ninja -C build
ninja: Entering directory `build'
[1/3] Compiling C object 'src/25a6634@@zlfo_ui@sha/zlfo_ui.c.o'.
FAILED: src/25a6634@@zlfo_ui@sha/zlfo_ui.c.o 
cc -Isrc/25a6634@@zlfo_ui@sha -Isrc -I../src -Isrc/.. -I../src/.. -I/usr/local/include -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -g -fvisibility=hidden -Wformat=2 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-sequence-point -Wignored-qualifiers -fPIC -pthread -MD -MQ 'src/25a6634@@zlfo_ui@sha/zlfo_ui.c.o' -MF 'src/25a6634@@zlfo_ui@sha/zlfo_ui.c.o.d' -o 'src/25a6634@@zlfo_ui@sha/zlfo_ui.c.o' -c ../src/zlfo_ui.c
In file included from ../src/zlfo_ui_theme.h:22:0,
                 from ../src/zlfo_ui.c:45:
/usr/local/include/ztoolkit/ztk.h:25:10: fatal error: log.h: No such file or directory
 #include "log.h"
          ^~~~~~~
compilation terminated.
[2/3] Linking target src/zlfo_dsp.so.
ninja: build stopped: subcommand failed.

$ ls /usr/local/include/ztoolkit/
ztk_app.h  ztk_color.h  ztk.h  ztk_knob.h  ztk_knob_with_label.h  ztk_label.h  ztk_widget.h  ztoolkit_config.h

**Comment by alex-tee** [comment]
ztoolkit is unreleased so there is no correct version dependency for it. i will release both ztoolkit and zlfo soon so this problem will go away.

for now, please use `meson build --wrap-mode=forcefallback` for ZLFO. it will pull in the latest ztoolkit for you

**Comment by grammoboy2** [comment]
On 20-02-2020 12:00, alex-tee wrote:
>
> ztoolkit is unreleased so there is no correct version dependency for 
> it. i will release both ztoolkit and zlfo soon so this problem will go 
> away.
>
> for now, please use |meson build --wrap-mode=forcefallback| for ZLFO. 
> it will pull in the latest ztoolkit for you
>
Should I uninstall my ztoolkit install?

**Comment by alex-tee** [comment]
yes, or alternatively you can just fetch the latest ztoolkit and reinstall it, then zlfo will build without the flag above.

**Comment by grammoboy2** [comment]
On 20-02-2020 12:04, alex-tee wrote:
>
> yes, or alternatively you can just fetch the latest ztoolkit and 
> reinstall it, then zlfo will build without the flag above.
>
>
After installation, the plugin is not found by Carla and lv2ls

**Comment by alex-tee** [comment]
what distro are you using and where did meson install it?

you can copy paste it into one of the paths in LV2_PATH (usually /usr/lib/lv2 or /usr/local/lib/lv2) but meson should take care of that normally

**Comment by grammoboy2** [comment]
On 20-02-2020 12:40, alex-tee wrote:
>
> what distro are you using and where did meson install it?
>
> you can copy paste it into one of the paths in LV2_PATH (usually 
> /usr/lib/lv2 or /usr/local/lib/lv2) but meson should take care of that 
> normally
>
>

Ubuntu 18.04

/usr/local/lib/x86_64-linux-gnu/lv2/ZLFO.lv2

**Comment by grammoboy2** [comment]
On 20-02-2020 12:40, alex-tee wrote:
>
> what distro are you using and where did meson install it?
>
> you can copy paste it into one of the paths in LV2_PATH (usually 
> /usr/lib/lv2 or /usr/local/lib/lv2) but meson should take care of that 
> normally
>
>
I can manually mv it to /usr/local/lib/lv2, but then I don't have a GUI


> ** ERROR (ztk_rsvg_load_svg): 12:57:31:338: An error occurred parsing 
> the SVG file at 
> /usr/local/lib/x86_64-linux-gnu/lv2/ZLFO.lv2/resources/sine.svg: (null)
> ** ERROR (zlfo_ui_theme_init): 12:57:31:338: Failed loading SVG: 
> /usr/local/lib/x86_64-linux-gnu/lv2/ZLFO.lv2/resources/sine.svg
>

**Comment by alex-tee** [comment]
ubuntu is problematic with meson. meson thinks the libdir is /usr/local/lib/x86_64-linux-gnu for some reason. i don't know what to do about it, i just use whatever meson says the libdir is, and that works for most distros. just copy it under /usr/local/lib/lv2/

**Comment by alex-tee** [comment]
can you run the host from the CLI? maybe there are helpful messages

**Comment by grammoboy2** [comment]
On 20-02-2020 13:07, alex-tee wrote:
>
> can you run the host from the CLI? maybe there are helpful messages
>
> —
>
I can add the (unusual) lv2 path to carla, now it works. Thanks.

**Comment by alex-tee** [comment]
cool. i also made it install in $PREFIX/lib/lv2 by default in the latest commit if you want to try that instead. closing this then
